# Site settings
title: Lauren E. Blake
email: <first initial><middle initial><lastname>@uchicago.edu
description: > # this means to ignore newlines until "baseurl:"
  Experimenting with GitHub sites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Lauren_E_Blake
github_username:  leblake

# Build settings
markdown: kramdown

theme: jekyll-theme-dinky
